-- MySQL Script generated by MySQL Workbench
-- Wed Jul 15 12:45:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adress` (
  `adress_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(50) NOT NULL,
  `number` VARCHAR(10) NULL,
  `floor` VARCHAR(10) NULL,
  `door` VARCHAR(10) NULL,
  `city` VARCHAR(50) NOT NULL,
  `pc` VARCHAR(10) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`adress_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provider` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `fax` VARCHAR(15) NULL,
  `nif` VARCHAR(9) NULL,
  `adress_adress_id` INT NOT NULL,
  PRIMARY KEY (`provider_id`),
  INDEX `fk_provider_adress1_idx` (`adress_adress_id` ASC),
  CONSTRAINT `fk_provider_adress1`
    FOREIGN KEY (`adress_adress_id`)
    REFERENCES `mydb`.`adress` (`adress_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(30) NOT NULL,
  `prescription_left` DECIMAL(4,3) NULL,
  `prescription_right` DECIMAL(4,3) NULL,
  `mount_color` VARCHAR(60) NULL,
  `colour_glassLeft` VARCHAR(30) NULL,
  `colour_glassRight` VARCHAR(30) NULL,
  `price` DECIMAL(6,3) NULL,
  PRIMARY KEY (`glasses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(40) NULL,
  `restration` DATE NULL,
  `recommended_by_id` INT NULL,
  `adress_adress_id` INT NOT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_recommender_idx` (`recommended_by_id` ASC),
  INDEX `fk_client_adress1_idx` (`adress_adress_id` ASC),
  CONSTRAINT `fk_recommender`
    FOREIGN KEY (`recommended_by_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_adress1`
    FOREIGN KEY (`adress_adress_id`)
    REFERENCES `mydb`.`adress` (`adress_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
