-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 16:47:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `adress_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(50) NOT NULL,
  `number` VARCHAR(10) NULL,
  `floor` VARCHAR(10) NULL,
  `door` VARCHAR(10) NULL,
  `city` VARCHAR(50) NOT NULL,
  `pc` VARCHAR(10) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`adress_id`))
ENGINE = InnoDB;

INSERT INTO address(street, number, floor, door, city, pc, country)
VALUES('Balmes', '120', '3', '2', 'Barcelona', '08008', 'Spain'),
('Atocha', '27', '2', '7', 'Madrid', '08001', 'Spain'),
('Diagonal', '512', '5', '1', 'Barcelona', '08006', 'Spain'),
('Sants', '85', '1', 'C', 'Barcelona', '08014', 'Spain');


-- -----------------------------------------------------
-- Table `mydb`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provider` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `fax` VARCHAR(15) NULL,
  `nif` VARCHAR(9) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`provider_id`),
  INDEX `fk_provider_adress1_idx` (`address_id` ASC),
  CONSTRAINT `fk_provider_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO provider(name, phone, fax, nif, address_id)
VALUES('Gloaria Supplies', '934578692', '934568791', 'B1257897', 1),
('TechGlass BCN', '935578468', '935578567', 'E4896533', 2),
('Mediterraneao', '933334476', '933334577', 'N9862568', 3);


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`brand_id`),
  INDEX `fk_brand_provider1_idx` (`provider_id` ASC),
  CONSTRAINT `fk_brand_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `mydb`.`provider` (`provider_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO brand(name, provider_id)
VALUES ('Xavier Garcia', 1),
('Kaleos', 3),
('Maller', 2),
('Kimze', 2);

-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(30) NOT NULL,
  `prescription_left` DECIMAL(4,3) NULL,
  `prescription_right` DECIMAL(4,3) NULL,
  `mount_color` VARCHAR(60) NULL,
  `colour_glassLeft` VARCHAR(30) NULL,
  `colour_glassRight` VARCHAR(30) NULL,
  `price` DECIMAL(6,3) NULL,
  `mount_type` ENUM('rimless', 'plastic', 'metal') NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_brand1_idx` (`brand_id` ASC),
  CONSTRAINT `fk_glasses_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO glasses(brand, prescription_left, prescription_right, mount_color, colour_glassLeft, colour_glassRight, price, mount_type, brand_id)
VALUES ('Xavier Garcia' , -1.250, -1.000, 'Black', 'Clear', 'Clear', 159.990, 'plastic', 1),
('Kaleos' , -2.500, -2.250, 'Matte Silver', 'Blue', 'Blue', 189.500, 'metal', 2),
('Maller' , 0.750, 0.500, 'Tortoiseshell', 'Green', 'Green', 220.000, 'plastic', 3),
('Kimze' , -3.000, -3.250, 'Gold', 'Brown', 'Brown', 275.750, 'rimless', 4);

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(15) NULL,
  `email` VARCHAR(40) NULL,
  `restration` DATE NULL,
  `recommended_by_id` INT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_recommender_idx` (`recommended_by_id` ASC),
  INDEX `fk_client_adress1_idx` (`adress_id` ASC),
  CONSTRAINT `fk_recommender`
    FOREIGN KEY (`recommended_by_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_client_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `mydb`.`address` (`adress_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO `mydb`.`client` (`name`, `phone`, `email`, `restration`, `recommended_by_id`, `adress_id`) 
VALUES ('Rodrigo Perez', '+346768729', 'rodrigo_p_casanov225@gmail.com', '2023-05-10', NULL, 1);

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;

INSERT INTO `employee` (`name`) VALUES 
('Mario Garcia'),
('Laura Martinez');

-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `sale_date` DATE NULL,
  `employee_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `glasses_id` INT NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sale_employee1_idx` (`employee_id` ASC),
  INDEX `fk_sale_client1_idx` (`client_id` ASC),
  INDEX `fk_sale_glasses1_idx` (`glasses_id` ASC),
  CONSTRAINT `fk_sale_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sale_glasses1`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `mydb`.`glasses` (`glasses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO `sale` (`sale_date`, `employee_id`, `client_id`, `glasses_id`) VALUES 
('2023-03-01', 1, 2, 1);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
